package com.letrogthien.auth.common;

public enum RoleName {
    ROLE_USER,
    ROLE_ADMIN,
    ROLE_MODERATOR,
    ROLE_SUPER_ADMIN,
    ROLE_GUEST,
    ROLE_MEMBER,
    ROLE_EDITOR,
    ROLE_VIEWER,
    ROLE_CONTRIBUTOR,
    ROLE_MANAGER,
    ROLE_OWNER,
    ROLE_SUPPORT,
    ROLE_DEVELOPER,
    ROLE_TESTER,
    ROLE_ANALYST,
    ROLE_AUDITOR;

}
